# Generated by Django 5.0.1 on 2024-01-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='year',
            new_name='name',
        ),
    ]
